---
- name: create www-data group
  group:
    name: "{{ webserver_user }}"
    state: present

- name: unlock www-data account
  user:
    name: "{{ webserver_user }}"
    shell: /bin/bash
    comment: WebServer Admin
    group: "{{ webserver_user }}"

- name: create nginx.conf
  template:
    src: nginx.conf-debian.j2
    dest: /etc/nginx/nginx.conf
    backup: yes

- name: create sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled/
    state: directory

- name: create nginx virtual host
  template:
    src: default-debian.j2
    dest: /etc/nginx/sites-enabled/{{ domain_name }}

- name: remove symlink from /etc/nginx/sites-enabled/
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

